feat: resolve bootstrap issues

diff --git a/bin/later b/bin/later
--- a/bin/later
+++ b/bin/later
@@ -8,8 +8,12 @@ else
 fi
 
 if ! which ansible-later >/dev/null; then
-    echo "Failed to detect later!"
-    exit 1
+    if test -d "${ROOT}/venv"; then
+        source "${ROOT}/venv/bin/activate"
+    else
+        echo "Failed to detect later!"
+        exit 1
+    fi
 fi
 
 pushd "${ROOT}" >/dev/null
diff --git a/bin/playbook b/bin/playbook
--- a/bin/playbook
+++ b/bin/playbook
@@ -8,8 +8,12 @@ else
 fi
 
 if ! which ansible-playbook >/dev/null; then
-    echo "Failed to detect playbook!"
-    exit 1
+    if test -d "${ROOT}/venv"; then
+        source "${ROOT}/venv/bin/activate"
+    else
+        echo "Failed to detect playbook!"
+        exit 1
+    fi
 fi
 
 if test -f "${ROOT}/.vaultpasswd"; then
